name: CI - Cross Platform (Zig Native)

on:
  push:
    branches: [ main, feature/data-oriented-design ]
  pull_request:
    branches: [ main ]

jobs:
  cross-compile:
    runs-on: ubuntu-latest  # Single runner - Zig handles cross-compilation!
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Zig
      uses: goto-bus-stop/setup-zig@v2
      with:
        version: '0.15.1'
    
    - name: Clone Nen Dependencies
      run: |
        cd ..
        git clone https://github.com/Nen-Co/nen-io.git
        git clone https://github.com/Nen-Co/nen-json.git  
        git clone https://github.com/Nen-Co/nen-net.git
    
    - name: Verify Zig Cross-Compilation Capabilities
      run: |
        echo "🚀 Zig Cross-Compilation Test"
        zig targets | head -20
        zig version
    
    - name: Cross-Compile for All Platforms
      run: |
        # Zig makes this incredibly simple!
        mkdir -p dist
        
        # Linux
        zig build -Dtarget=x86_64-linux-gnu --release=safe
        mkdir -p dist/linux-x64 && cp -r zig-out/bin/* dist/linux-x64/
        
        zig build -Dtarget=aarch64-linux-gnu --release=safe  
        mkdir -p dist/linux-arm64 && cp -r zig-out/bin/* dist/linux-arm64/
        
        # macOS
        zig build -Dtarget=x86_64-macos --release=safe
        mkdir -p dist/macos-x64 && cp -r zig-out/bin/* dist/macos-x64/
        
        zig build -Dtarget=aarch64-macos --release=safe
        mkdir -p dist/macos-arm64 && cp -r zig-out/bin/* dist/macos-arm64/
        
        # Windows  
        zig build -Dtarget=x86_64-windows-gnu --release=safe
        mkdir -p dist/windows-x64 && cp -r zig-out/bin/* dist/windows-x64/
        
        echo "✅ Cross-compilation completed!"
        
    - name: Test Native Build
      run: |
        # Test on Linux (native to runner)
        zig build -Dtarget=x86_64-linux-gnu --release=safe
        zig build test-unit
        zig build test-tcp
        
    - name: Verify All Binaries
      run: |
        echo "📦 Generated Binaries:"
        find dist/ -name "*" -type f -exec file {} \;
        
    - name: Upload Cross-Platform Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: nendb-cross-platform
        path: dist/

  # Optional: Test on actual target platforms
  test-platforms:
    needs: cross-compile
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    
    runs-on: ${{ matrix.os }}
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Zig  
      uses: goto-bus-stop/setup-zig@v2
      with:
        version: '0.15.1'
        
    - name: Clone Nen Dependencies
      run: |
        cd ..
        git clone https://github.com/Nen-Co/nen-io.git
        git clone https://github.com/Nen-Co/nen-json.git  
        git clone https://github.com/Nen-Co/nen-net.git
        
    - name: Test Native Build & Run
      run: |
        zig build --release=safe
        zig build test-unit
        
    - name: Quick TCP Test
      if: matrix.os != 'windows-latest'  # Skip on Windows for now
      run: |
        zig build test-tcp
