name: CI Matrix - Build Native + WASM

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Zig
        uses: goto-bus-stop/setup-zig@v2
        with:
          version: '0.15.1'

      - name: Setup dependencies
        run: |
          echo "🔗 Setting up dependencies"
          cd ..
          git clone https://github.com/Nen-Co/nen-core.git
          git clone https://github.com/Nen-Co/nen-io.git
          git clone https://github.com/Nen-Co/nen-json.git
          git clone https://github.com/Nen-Co/nen-net.git
          cd nen-db

      - name: Build native executable
        run: |
          echo "Building native executable on $RUNNER_OS"
          # Build the default native executable
          zig build -Doptimize=ReleaseFast

      - name: Build WASM module (optional)
        run: |
          # Try to build the WASM artifact; failing to build WASM should not fail the whole job
          zig build nendb-wasm || true

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: nendb-${{ matrix.os }}
          path: |
            zig-out
            wasm
          retention-days: 7
