name: Release - Build Artifacts and Upload
on:
  push:
    tags: ['v*']

jobs:
  build-cross-platform:
    name: Build artifacts (matrix)
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - os: linux
            target: x86_64-linux-gnu
            arch: x86_64
            ext: ""
            archive: tar.gz
          - os: macos
            target: x86_64-macos-none
            arch: x86_64
            ext: ""
            archive: tar.gz
          - os: macos
            target: aarch64-macos-none
            arch: aarch64
            ext: ""
            archive: tar.gz
          - os: windows
            target: x86_64-windows-gnu
            arch: x86_64
            ext: ".exe"
            archive: zip

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Zig
        uses: goto-bus-stop/setup-zig@v2
        with:
          version: '0.15.1'

      - name: Build for matrix target
        run: |
          echo "Building for ${{ matrix.target }}"
          zig build -Dtarget=${{ matrix.target }} -Drelease-fast || zig build -Dtarget=${{ matrix.target }}

      - name: Gather binaries
        run: |
          mkdir -p artifacts/${{ matrix.os }}-${{ matrix.arch }}
          cp -v zig-out/bin/nendb${{ matrix.ext }} artifacts/${{ matrix.os }}-${{ matrix.arch }}/ || true
          cp -v zig-out/bin/nendb-server${{ matrix.ext }} artifacts/${{ matrix.os }}-${{ matrix.arch }}/ || true
          cp -v README.md artifacts/${{ matrix.os }}-${{ matrix.arch }}/ || true
          cp -v LICENSE artifacts/${{ matrix.os }}-${{ matrix.arch }}/ || true

      - name: Archive artifacts
        run: |
          cd artifacts
          TAG=${GITHUB_REF_NAME:-dev}
          if [ "${{ matrix.archive }}" = "zip" ]; then
            zip -r nen-${TAG}-${{ matrix.os }}-${{ matrix.arch }}.zip ${{ matrix.os }}-${{ matrix.arch }}
          else
            tar -czf nen-${TAG}-${{ matrix.os }}-${{ matrix.arch }}.tar.gz ${{ matrix.os }}-${{ matrix.arch }}
          fi

      - name: Compute checksums
        run: |
          cd artifacts
          TAG=${GITHUB_REF_NAME:-dev}
          if [ "${{ matrix.archive }}" = "zip" ]; then
            sha256sum nen-${TAG}-${{ matrix.os }}-${{ matrix.arch }}.zip > nen-${TAG}-${{ matrix.os }}-${{ matrix.arch }}.sha256
          else
            sha256sum nen-${TAG}-${{ matrix.os }}-${{ matrix.arch }}.tar.gz > nen-${TAG}-${{ matrix.os }}-${{ matrix.arch }}.sha256
          fi

      - name: Upload artifacts to workflow
        uses: actions/upload-artifact@v4
        with:
          name: nen-${{ matrix.os }}-${{ matrix.arch }}
          path: artifacts/nen-*${{ matrix.os }}-${{ matrix.arch }}.*

  publish-release:
    name: Publish release (tag)
    needs: [build-cross-platform]
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: release-assets

      - name: Create GitHub Release and upload assets
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          files: release-assets/**/nen-${{ github.ref_name }}-*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
