name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Zig 0.14.1
        uses: ziglang/setup-zig@v0.4
        with:
          version: 0.14.1
      - name: Build
        shell: bash
        run: |
          set -euo pipefail
          zig build -Drelease-safe
          mkdir -p dist
          if [ "${{ runner.os }}" = "Windows" ]; then
            cp zig-out/bin/nen.exe dist/nen-windows-x86_64.exe
            powershell -Command "Compress-Archive -Path dist/nen-windows-x86_64.exe -DestinationPath dist/nen-windows-x86_64.zip"
          elif [ "${{ runner.os }}" = "macOS" ]; then
            cp zig-out/bin/nen dist/nen-macos-universal
            tar -czf dist/nen-macos-universal.tar.gz -C dist nen-macos-universal
            rm dist/nen-macos-universal
          else
            cp zig-out/bin/nen dist/nen-linux-x86_64
            tar -czf dist/nen-linux-x86_64.tar.gz -C dist nen-linux-x86_64
            rm dist/nen-linux-x86_64
          fi
      - name: Checksums
        if: runner.os != 'Windows'
        run: |
          set -euo pipefail
          (cd dist && sha256sum *.tar.gz > SHA256SUMS)
      - name: Checksums (Windows)
        if: runner.os == 'Windows'
        run: |
          powershell -Command "Get-FileHash dist/nen-windows-x86_64.zip -Algorithm SHA256 | ForEach-Object { $_.Hash + '  nen-windows-x86_64.zip' } | Out-File -Encoding ASCII dist/SHA256SUMS"
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ runner.os }}-artifacts
          path: dist/*

  release:
    name: Publish Release
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          path: collected
      - name: List artifacts
        run: |
          ls -R collected
      - name: Merge checksums
        run: |
          set -euo pipefail
          mkdir final
          cp collected/**/nen-* final/ 2>/dev/null || true
          cp collected/**/SHA256SUMS final/ 2>/dev/null || true
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          files: final/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
